import { Machine } from "@/app/types/Machine";

export const machineData: Machine[] = [
  // {
  //   name: "1,8t Bagger",
  //   slug: "18t-bagger",
  //   model: "Kubota HE28",
  //   category: "Bagger",
  //   image: {
  //     url: "/images/machines/Kubota_HE28.jpeg",
  //     alt: "Gelber Bagger auf Hügel",
  //   },
  //   price: { perDay: 100, perWeek: 700, perMonth: 3000 },
  //   content: {
  //     title: "",
  //     description: "",
  //     specifications: {
  //       dimensions: {
  //         width: "980/1 350 mm",
  //         height: "2 390 mm",
  //         length: "3 640 mm",
  //         weight: "1 825 kg",
  //         volume: "0.04 m³",
  //       },
  //       power: "14.6 kW 2 400 U/min",
  //       workingRange: {
  //         maxDepth: "2 360 mm",
  //         maxReach: "4 000 mm",
  //         minSwingRadius: "1 705 mm",
  //         bucketBreakoutForceISO: "15.2 kN",
  //         armTearOutForceISO: "9.2 kN",
  //       },
  //     },
  //   },
  //   inventory: {
  //     hennef: [{ articleId: "F5596I" }],
  //     mannheim: [{ articleId: "2AT3K3" }],
  //     // mannheim: [{ articleId: "2AT3K3", priceOverride: { perDay: 110 } }],
  //     bruchsal: [{ articleId: "3HIBNP" }, { articleId: "XYZ123" }],
  //   },
  // },
  //   {
  //   name: "1,8t Bagger",
  //   slug: "18t-bagger",
  //   model: "Kubota HE28",
  //   category: "Bagger",
  //   image: {
  //     url: "/images/machines/Kubota_HE28.jpeg",
  //     alt: "Gelber Bagger auf Hügel",
  //   },
  //   price: { perDay: 100, perWeek: 700, perMonth: 3000 },
  //   content: {
  //     title: "",
  //     description: "",
  //     specifications: {
  //       dimensions: {
  //         width: "980/1 350 mm",
  //         height: "2 390 mm",
  //         length: "3 640 mm",
  //         weight: "1 825 kg",
  //         volume: "0.04 m³",
  //       },
  //       power: "14.6 kW 2 400 U/min",
  //       workingRange: {
  //         maxDepth: "2 360 mm",
  //         maxReach: "4 000 mm",
  //         minSwingRadius: "1 705 mm",
  //         bucketBreakoutForceISO: "15.2 kN",
  //         armTearOutForceISO: "9.2 kN",
  //       },
  //     },
  //   },
  //   inventory: {
  //     hennef: [{ articleId: "F5596I" }],
  //     mannheim: [{ articleId: "2AT3K3" }],
  //     // mannheim: [{ articleId: "2AT3K3", priceOverride: { perDay: 110 } }],
  //     bruchsal: [{ articleId: "3HIBNP" }, { articleId: "XYZ123" }],
  //   },
  // },
  //   {
  //   name: "1,8t Bagger",
  //   slug: "18t-bagger",
  //   model: "Kubota HE28",
  //   category: "Bagger",
  //   image: {
  //     url: "/images/machines/Kubota_HE28.jpeg",
  //     alt: "Gelber Bagger auf Hügel",
  //   },
  //   price: { perDay: 100, perWeek: 700, perMonth: 3000 },
  //   content: {
  //     title: "",
  //     description: "",
  //     specifications: {
  //       dimensions: {
  //         width: "980/1 350 mm",
  //         height: "2 390 mm",
  //         length: "3 640 mm",
  //         weight: "1 825 kg",
  //         volume: "0.04 m³",
  //       },
  //       power: "14.6 kW 2 400 U/min",
  //       workingRange: {
  //         maxDepth: "2 360 mm",
  //         maxReach: "4 000 mm",
  //         minSwingRadius: "1 705 mm",
  //         bucketBreakoutForceISO: "15.2 kN",
  //         armTearOutForceISO: "9.2 kN",
  //       },
  //     },
  //   },
  //   inventory: {
  //     hennef: [{ articleId: "F5596I" }],
  //     mannheim: [{ articleId: "2AT3K3" }],
  //     // mannheim: [{ articleId: "2AT3K3", priceOverride: { perDay: 110 } }],
  //     bruchsal: [{ articleId: "3HIBNP" }, { articleId: "XYZ123" }],
  //   },
  // },
  //   {
  //   name: "1,8t Bagger",
  //   slug: "18t-bagger",
  //   model: "Kubota HE28",
  //   category: "Bagger",
  //   image: {
  //     url: "/images/machines/Kubota_HE28.jpeg",
  //     alt: "Gelber Bagger auf Hügel",
  //   },
  //   price: { perDay: 100, perWeek: 700, perMonth: 3000 },
  //   content: {
  //     title: "",
  //     description: "",
  //     specifications: {
  //       dimensions: {
  //         width: "980/1 350 mm",
  //         height: "2 390 mm",
  //         length: "3 640 mm",
  //         weight: "1 825 kg",
  //         volume: "0.04 m³",
  //       },
  //       power: "14.6 kW 2 400 U/min",
  //       workingRange: {
  //         maxDepth: "2 360 mm",
  //         maxReach: "4 000 mm",
  //         minSwingRadius: "1 705 mm",
  //         bucketBreakoutForceISO: "15.2 kN",
  //         armTearOutForceISO: "9.2 kN",
  //       },
  //     },
  //   },
  //   inventory: {
  //     hennef: [{ articleId: "F5596I" }],
  //     mannheim: [{ articleId: "2AT3K3" }],
  //     // mannheim: [{ articleId: "2AT3K3", priceOverride: { perDay: 110 } }],
  //     bruchsal: [{ articleId: "3HIBNP" }, { articleId: "XYZ123" }],
  //   },
  // },
  //   {
  //   name: "1,8t Bagger",
  //   slug: "18t-bagger",
  //   model: "Kubota HE28",
  //   category: "Bagger",
  //   image: {
  //     url: "/images/machines/Kubota_HE28.jpeg",
  //     alt: "Gelber Bagger auf Hügel",
  //   },
  //   price: { perDay: 100, perWeek: 700, perMonth: 3000 },
  //   content: {
  //     title: "",
  //     description: "",
  //     specifications: {
  //       dimensions: {
  //         width: "980/1 350 mm",
  //         height: "2 390 mm",
  //         length: "3 640 mm",
  //         weight: "1 825 kg",
  //         volume: "0.04 m³",
  //       },
  //       power: "14.6 kW 2 400 U/min",
  //       workingRange: {
  //         maxDepth: "2 360 mm",
  //         maxReach: "4 000 mm",
  //         minSwingRadius: "1 705 mm",
  //         bucketBreakoutForceISO: "15.2 kN",
  //         armTearOutForceISO: "9.2 kN",
  //       },
  //     },
  //   },
  //   inventory: {
  //     hennef: [{ articleId: "F5596I" }],
  //     mannheim: [{ articleId: "2AT3K3" }],
  //     // mannheim: [{ articleId: "2AT3K3", priceOverride: { perDay: 110 } }],
  //     bruchsal: [{ articleId: "3HIBNP" }, { articleId: "XYZ123" }],
  //   },
  // },
  //   {
  //   name: "1,8t Bagger",
  //   slug: "18t-bagger",
  //   model: "Kubota HE28",
  //   category: "Bagger",
  //   image: {
  //     url: "/images/machines/Kubota_HE28.jpeg",
  //     alt: "Gelber Bagger auf Hügel",
  //   },
  //   price: { perDay: 100, perWeek: 700, perMonth: 3000 },
  //   content: {
  //     title: "",
  //     description: "",
  //     specifications: {
  //       dimensions: {
  //         width: "980/1 350 mm",
  //         height: "2 390 mm",
  //         length: "3 640 mm",
  //         weight: "1 825 kg",
  //         volume: "0.04 m³",
  //       },
  //       power: "14.6 kW 2 400 U/min",
  //       workingRange: {
  //         maxDepth: "2 360 mm",
  //         maxReach: "4 000 mm",
  //         minSwingRadius: "1 705 mm",
  //         bucketBreakoutForceISO: "15.2 kN",
  //         armTearOutForceISO: "9.2 kN",
  //       },
  //     },
  //   },
  //   inventory: {
  //     hennef: [{ articleId: "F5596I" }],
  //     mannheim: [{ articleId: "2AT3K3" }],
  //     // mannheim: [{ articleId: "2AT3K3", priceOverride: { perDay: 110 } }],
  //     bruchsal: [{ articleId: "3HIBNP" }, { articleId: "XYZ123" }],
  //   },
  // },
  //   {
  //   name: "1,8t Bagger",
  //   slug: "18t-bagger",
  //   model: "Kubota HE28",
  //   category: "Bagger",
  //   image: {
  //     url: "/images/machines/Kubota_HE28.jpeg",
  //     alt: "Gelber Bagger auf Hügel",
  //   },
  //   price: { perDay: 100, perWeek: 700, perMonth: 3000 },
  //   content: {
  //     title: "",
  //     description: "",
  //     specifications: {
  //       dimensions: {
  //         width: "980/1 350 mm",
  //         height: "2 390 mm",
  //         length: "3 640 mm",
  //         weight: "1 825 kg",
  //         volume: "0.04 m³",
  //       },
  //       power: "14.6 kW 2 400 U/min",
  //       workingRange: {
  //         maxDepth: "2 360 mm",
  //         maxReach: "4 000 mm",
  //         minSwingRadius: "1 705 mm",
  //         bucketBreakoutForceISO: "15.2 kN",
  //         armTearOutForceISO: "9.2 kN",
  //       },
  //     },
  //   },
  //   inventory: {
  //     hennef: [{ articleId: "F5596I" }],
  //     mannheim: [{ articleId: "2AT3K3" }],
  //     // mannheim: [{ articleId: "2AT3K3", priceOverride: { perDay: 110 } }],
  //     bruchsal: [{ articleId: "3HIBNP" }, { articleId: "XYZ123" }],
  //   },
  // },
] as const;
