import type { Metadata } from "next";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <>
        <script
          type="module"
          src="https://cdn.rtr-io.com/widgets.js"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.RTR_ACCESS_TOKEN = 'W714a858bbc2ca6b6ff34cbbdcc2188a8';
            `,
          }}
        ></script>
      </>

      <body>
        {children}
        <rtr-checkout></rtr-checkout>
      </body>
    </html>
  );
}
