import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <>
        <Script
          src="https://cdn.rtr-io.com/widgets.js"
          strategy="afterInteractive"
          type="module"
        />
        <Script
          id="rtr-access-token"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `window.RTR_ACCESS_TOKEN = 'Wd1285b3297330ea1ae4731ab48fe16fe';`,
          }}
        />
      </>

      <body>
        {children}
        <rtr-checkout></rtr-checkout>
      </body>
    </html>
  );
}
